backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page

          - label: Title
            name: title
            widget: string

      - file: src/pages/information.md
        label: Information
        name: information
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: information-page

          - label: Title
            name: title
            widget: hidden
            default: Information

          - label: Biography
            name: bio
            widget: markdown
            buttons: [link]
            editorComponents: []

          - label: Clients
            name: clients
            widget: markdown
            buttons: [heading-four, bulleted-list]
            editorComponents: []

          - label: Contact information
            name: contact
            widget: list
            summary: '{{fields.title}}'
            fields:
              - label: Title
                name: title
                widget: string
              - label: Text
                name: text
                widget: string
              - label: Link
                name: link
                widget: string

  - name: projects
    label: Projects
    folder: src/pages/projects
    create: true
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: project-page

      - label: Title
        name: title
        widget: string

      - label: Date
        name: date
        widget: datetime
        default: ''
        dateFormat: 'DD.MM.YYYY' # e.g. 24.12.2021
        timeFormat: 'HH:mm' # e.g. 21:07
        format: 'LLL'
        pickerUtc: false
        hint: Projects are sorted by this date field in descending order (newest first). This won't show on the website anywhere. Tap "Now" to add the current date+time.

      - label: Category
        name: category
        widget: select
        options:
          - label: Editorial
            value: Editorial
          - label: Commercial
            value: Commercial
          - label: Film
            value: Film

      - label: Featured image
        name: featuredImage
        widget: image

      - label: Images
        name: images
        widget: list
        summary: '{{fields.image}}'
        fields:
          - label: Image
            name: image
            widget: image
