name: Publish

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM cache folder
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Gatsby cache folder
          uses: actions/cache@v2
          with:
            path: .cache
            key: ${{ runner.os }}-cache-gatsby
            restore-keys: |
              ${{ runner.os }}-cache-gatsby

        - name: Gatsby public folder
          uses: actions/cache@v2
          with:
            path: public/
            key: ${{ runner.os }}-public-gatsby
            restore-keys: |
              ${{ runner.os }}-public-gatsby

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Build
        run: yarn build --log-pages
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          NODE_ENV: production
            CI: true

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftp.pamelabellafesta.se/
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
